### PR TITLE
Changes to have libcpath_path_make_directory use CreateDirectoryW

### PR DESCRIPTION
**Pull request by ScaledLizard**
libcpath_path_make_directory: path is stored as UTF-8, so we cannot use CreateDirectoryA on Windows. Instead, the path has to be converted to UTF-16 and CreateDirectoryW needs to be used.

I tried to match your coding style, but maybe there is a function somewhere in libyal that simplifies the string conversions? Also, I hope I got the arguments for libcerror right.

Windows 10 (as of build 1903) and 11 support processes that use UTF-8 for file access with special manifests, but it seems libyal is written with long-term support of older operating system versions in mind.

https://learn.microsoft.com/en-us/windows/apps/design/globalizing/use-utf8-code-page

### CODE REVIEW

**Comment by joachimmetz** [comment]
Why not use libcpath_path_change_directory_wide instead?

**Comment by ScaledLizard** [comment]
> Why not use libcpath_path_change_directory_wide instead?

There is a function libcpath_path_make_directory_wide, but it takes const wchar_t *directory_name, so a conversion is still needed.

**Comment by joachimmetz** [comment]
> There is a function libcpath_path_make_directory_wide, but it takes const wchar_t *directory_name, so a conversion is still needed.

yes but there is no need to change this library for that

**Comment by joachimmetz** [comment]
Closing this for now, given it is unclear why this change is necessary

**Pull request closed without merging**
