### PR TITLE
add: new path type ( LIBCPATH_TYPE_DRIVE )

### PR DESCRIPTION
**Pull request by yasulib**
I wanted to open `\\.\C:` using libfsntfs so I wrote the following code:
```c
result = libfsntfs_volume_open(
                   volume,
                   "\\\\.\\C:",
                   LIBFSNTFS_OPEN_READ,
                   &error
);
```
Then the following error occurred.
```
[ERROR] Result: -1
libcsplit_narrow_split_string_get_number_of_segments: invalid split string.
libcpath_path_get_full_path: unable to retrieve number of path string segments.
libbfio_file_set_name: unable to determine full path.
libfsntfs_volume_open: unable to set filename in file IO handle.
```
When I examined the cause, I noticed that `libcpath_path_get_full_path()` of libcpath does not correspond to `\\.\C:`. Therefore, when `\\.\C:` is input to the function, I modified so that `LIBCPATH_TYPES` is judged as `LIBCPATH_TYPE_DRIVE`.

However, I only read a part of libcpath and libfsntfs, so I don't know how this modification affects other libraries.
If there were other good ways, please tell me.

### CODE REVIEW

**Comment by joachimmetz** [comment]
There are more challenges when using '\\.\C'

* libfsntfs is (currently) not built for (live) analysing a file system that can change; 
* the '\\.\C' device driver does not expose the last sector by default (also see: https://github.com/libyal/libcfile/issues/2)

**Comment by yasulib** [comment]
Thank you for the knowledge.
I want to retrieve `$MFT`, `$UsnJrnl:$J` and so on.

> libfsntfs is (currently) not built for (live) analysing a file system that can change;

If the file is modified after libfsntfs_volume_open called, is it perhaps that data run list is changed and correct file cannot be retrieved? In that case, I should call libfsntfs_volume_open() just before obtaining the file immediately after getting the file to minimize the impact?

**Comment by joachimmetz** [comment]
> I want to retrieve $MFT, $UsnJrnl:$J and so on.

what do you mean with "retrieve"? make a copy or parse structures?

> In that case, I should call libfsntfs_volume_open() just before obtaining the file immediately after getting the file to minimize the impact?

The live file system is controlled by the kernel driver, libfsntfs runs in user space, any part of the file system can change during/after the call to libfsntfs_volume_open or any other libfsntfs function. You either take a margin of error for granted of apply an alternative solution. One option to minimize impact of changes is to reduce the amount of information cached by the library, this however comes with a performance penalty.

**Comment by yasulib** [comment]
> what do you mean with "retrieve"? make a copy or parse structures?

I want to make a copy.
I got it that the risk of copying from live and reducing the risk is a trade-off from performance penalty.

**Comment by joachimmetz** [comment]
> I want to make a copy.

The "window of potential data changes" should be more contained in that case and with `$UsnJrnl:$J` you likely only want to copy the non-sparse regions to improve speed.

I've made some changes to address https://github.com/libyal/libcfile/issues/2 and will have a look at your proposed changes to libcpath as soon as time permits. See if I can add Windows device file support to libfsntfs. 

To be verbose libfsntfs is considered experimental at this point in time, when time permits I'm planning to make changes for usage in dfVFS.

**Comment by joachimmetz** [comment]
I did some digging but these changes do not provide you with the functionality to read from `\\.\C:` you describe. I've added file alignment support to libcfile to support `\\.\C:` devices. See: https://github.com/libyal/libcfile/commit/ca0927d2612d00c986807611bca7567d5c0e30c3

**Review by joachimmetz — COMMENTED** [review]
Not merging, does not help to provide the described functionality

**Pull request closed without merging**
